version: '2'

services:
  fitness-php72:
    container_name: fitness-ntf-php72
    build:
      context: ./php
      args:
        - http_proxy
        - HTTP_PROXY
        - https_proxy
        - HTTPS_PROXY
        - no_proxy
    volumes:
      - "../src:/var/www/html"
    restart: always
    environment:
      - TZ=Europe/Moscow
      - PHP_MEMORY_LIMIT=256M
      - PHP_POST_MAX_SIZE=8M
      - PHP_MAX_FILE_UPLOADS=20
      - PHP_UPLOAD_MAX_FILESIZE=2M
      - PHP_SESSION_SAVE_HANDLER=files
      - PHP_SESSION_SAVE_PATH="/tmp/session"
      - PHP_MAX_INPUT_VARS=1000
      - PHP_MAX_EXECUTION_TIME=0
      - PHP_DATE_TIMEZONE=Europe/Moscow
      - PHP_LOG_ERRORS=1
      - PHP_LOG_ERRORS_MAX_LEN=1024
      - PHP_XDEBUG_IDEKEY=diversantvlz
      - PHP_XDEBUG_DEFAULT_ENABLE=0
      - PHP_XDEBUG_REMOTE_ENABLE=1
      - PHP_XDEBUG_REMOTE_AUTOSTART=0
      - PHP_XDEBUG_REMOTE_CONNECT_BACK=0
      - PHP_XDEBUG_PROFILER_ENABLE=0
      - PHP_XDEBUG_REMOTE_HOST=192.168.0.4

  fitness-nginx:
    container_name: fitness-ntf-nginx
    restart: always
    image: nginx:latest
    depends_on:
      - fitness-php72
    ports:
      - "8083:80"
    volumes:
      - "./nginx/logs:/var/log/nginx"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/fitness.notification.local.template:/etc/nginx/conf.d/fitness.notification.local.template"
      - "../src:/var/www/html"
    environment:
      - NGINX_HOST=fitness.notification.local
      - NGINX_PORT=80
      - PHP_FPM_HOST=fitness-php72
      - PHP_FPM_PORT=9000
      - TZ=Europe/Moscow
    # command подменит в шаблоне вхоста переменные на значения из заданных переменных окружения
    command: /bin/bash -c "envsubst \"`for v in $$(compgen -v);do printf '$${%s} ' $$v;done`'\" < /etc/nginx/conf.d/fitness.notification.local.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  fitness-mysql:
    container_name: fitness-ntf-mysql
    image: "mysql/mysql-server:5.7.21"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=devroot
      - TZ="Europe/Moscow"
    ports:
      - "3307:3306"
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql"