swiftmailer:
    transport:        '%env(MAIL_TRANSPORT)%'
    username:         '%env(MAIL_USERNAME)%'
    password:         '%env(MAIL_PASSWORD)%'
    host:             '%env(MAIL_HOST)%'
    port:             '%env(MAIL_PORT)%'
    encryption:       '%env(MAIL_ENCRYPTION)%'
    auth-mode:        '%env(MAIL_AUTH_MODE)%'
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false