homepage:
    path: /
    controller: App\Controller\IndexController::index

reset_password:
    path: /reset-password/{slug}
    controller: App\Controller\SecurityController::resetUrl

group_lessons:
    path: /group-lessons
    controller: App\Controller\LessonController::groupList

subscribe_lesson_type:
    path: /group-lessons/{code}/subscribe
    controller: App\Controller\LessonController::subscribeLessonType

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"