fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

homepage:
    path: /
    controller: App\Controller\IndexController::index

reset_password:
    path: /reset-password/{slug}
    controller: App\Controller\SecurityController::resetUrl

group_lessons:
    path: /group-lessons
    controller: App\Controller\LessonController::groupListAction

subscribe_lesson_type:
    path: /group-lessons/{code}/subscribe/{redirectRoute}
    controller: App\Controller\LessonController::subscribeLessonTypeAction

un_subscribe_lesson_type:
    path: /group-lessons/{code}/un_subscribe_lesson_type/{redirectRoute}
    controller: App\Controller\LessonController::unSubscribeLessonTypeAction

fos_user_profile_show:
    path: /profile
    controller: App\Controller\ProfileController::showAction

change_channel_notification:
    path: /channel/change/notification/{channel}
    controller: App\Controller\ProfileController::changeChannelNotificationAction